### ISSUE TITLE
StopIteration exception

### ISSUE THREAD

**Issue by EemeliSaari** [aajanki/spacy-fi#2]
Hi,

Spotted this weird bug that might be related to both Voikko implementation and the way word possessives are handled in the spacy-fi.

```
~/miniconda3/envs/.env/lib/python3.7/site-packages/spacy_fi_experimental_web_md/fi.py in _remove_possessive_suffix(self, word, analysis)
    946         """
    947         suffixes = self.possessive_suffixes[analysis["POSSESSIVE"]]
--> 948         suffix = next((s for s in suffixes if word.endswith(s)))
    949         if not suffix:
    950             return word
```

**To reproduce:**
```python
import spacy

nlp = spacy.load('spacy_fi_experimental_web_md')

doc = nlp('Varmasti välit pystyy pitämään ja voisihan maskiakin käyttää.')
for t in doc:
    print(f'{t.lemma_}\t{t.pos_}')
```

The word that causes issues here is the `voisihan`.

**My environment:**
- Python 3.7.11
- spacy_fi_experimental_web_md 0.7.1
- Libvoikko 4.3.1

This problem could be fixed by replacing the `next`operator using something like this:
```python
def _remove_possessive_suffix(self, word, analysis):
    """Removes possessive suffix from the word.
    Example: "kanssamme" -> "kanssa"
    """
    suffixes = self.possessive_suffixes[analysis["POSSESSIVE"]]
    matches = [s for s in suffixes if word.endswith(s)]
    if not matches:
        return word
    suffix = matches[0]
```

Interestingly the same issue appears only in specific sentences so not sure if that would fix the underlying issue but at least make the method stable.

**Comment by aajanki** [comment]
Good catch! I fixed this by adding a default value to the next-operator. At least I think that should fix it, but I'm not able to confirm it because I can't reproduce the bug even with your test program.

You can to test it by pulling the latest master branch or wait until I publish a new version for spacy 3.2 in a couple of days.

**Comment by EemeliSaari** [comment]
Interestingly I could reproduce it on native Ubuntu 20.04 as well as in Docker images that use the same distro as base (not on the default Python images for example). I tried to run this snippet on different environments

```python
from libvoikko import Voikko
print(Voikko('fi').analyze('voisihan'))
```

And the order of the analysis results change depending on the environment you run it. This could explain why you could not reproduce the bug since in some cases the correct one `voida` just happens to be the first item on the list.
